export const headerContainer = {
    hidden:{
        opacity:0,
        x:-50
    },
    visible:{
        opacity:1,
        x:0,
        transition:{
            duration:0.5,
            staggerChildren:0.3,
            when:'beforeChildren'
        }
    }
}
export const header = {
    hidden:{
        opacity:0,
        x:-50
    },
    visible:{
        opacity:1,
        x:0,
        transition:{
            duration:0.5,
        }
    }
} 
export const headerReversed = {
    hidden:{
        opacity:0,
        x:50
    },
    visible:{
        opacity:1,
        x:0,
        transition:{
            duration:0.5,
        }
    }
} 